### ISSUE TITLE
Semantic point cloud of objects

### ISSUE THREAD

**Issue by Minzhao1995** [vincentcartillier/Semantic-MapNet#3]
Hi,

Thanks for your amazing works. According to my understanding, the GT semantic maps are obtained directly from global object point clouds. I would like to know to generate that point clouds, as the semantic point clouds directly generated from the depth and semantic annotations are noisy. 

Did you use some postprocessing methods like filter out outlier points with GT bounding boxes? Or generate from the semantic.ply in the mp3d dataset?

Thanks!

**Comment by vincentcartillier** [comment]
Hi Minzhao,

Thanks for your interest in this project!
Indeed creating that object point cloud by unprojecting semantic pixels using depth is noisy. This is due to a slight difference in geometry between the depth and semantic meshes in MP3D.

Rather in this project the GT object point clouds are directly built from the semantic mesh itself (semantic.ply file). We dense sampled 3D points from the triangles of objects of interest from that mesh.

**Comment by Minzhao1995** [comment]
> Hi Minzhao,
> 
> Thanks for your interest in this project!
> Indeed creating that object point cloud by unprojecting semantic pixels using depth is noisy. This is due to a slight difference in geometry between the depth and semantic meshes in MP3D.
> 
> Rather in this project the GT object point clouds are directly built from the semantic mesh itself (semantic.ply file). We dense sampled 3D points from the triangles of objects of interest from that mesh.

Thanks very much for your reply!
